### PR TITLE
OptionDescriptors missing

### PR DESCRIPTION
**Pull request by jacoborous**
Small change, build would not work otherwise.

### CODE REVIEW

**Comment by lukasstadler** [comment]
Hi!
Looks like this PR is work-in-progress, please let me know if you'd like to get some more feedback on your changes.
I'd also be curious whether you're trying to use grCUDA for a specific use case, or just giving it a try in general.
- Lukas

**Comment by jacoborous** [comment]
Hi! Thanks for taking time to have a look. Still navigating the codebase, but I'm interested in Graal/Truffle in general, especially Sulong, mainly as a way to build much better interfaces with the native host/devices. An application I am working on right now has been using JCUDA and javacpp OpenBLAS as it's compute backend, and I was curious about how this library would compare to JCuda in terms of overall quality of API, as well as extensibility.

For this PR, I simply added a few lines that seemed to be missing in order to allow it to build, but I've made some additional changes to my branch that are not ready to be submitted yet. Please let me know if there is a more 'canonical' way of adding the OptionDescriptors than what I did and I can change that.

**Comment by jacoborous** [comment]
That said, it seems those extra commits got added to this PR, sorry about that, so I will close it for now.

**Comment by lukasstadler** [comment]
wrt. OptionDescriptors: that should all happen automatically based on the Option annotation.
Annotation processors are used extensively in Truffle (and thus also in grCUDA), so the `GrCUDAOptionsOptionDescriptors` referenced in `GrCUDALanguage` should be generated automatically during the build process.
If you're working with an IDE, e.g., Eclipse, make sure to create the project configuration via `mx ideinit` and import it, as opposed to creating the project config manually.

**Comment by muellren** [comment]
@jacoborous Alternatively, you can build grCUDA outside of the IDE using [mx](https://github.com/graalvm/mx). This should work as described in the [build instructions](https://github.com/NVIDIA/grCUDA#instructions-to-build-grcuda-from-sources) for grCUDA.

Do let us know if features required for your application are missing in grCUDA. We are also interested to learn about how grCUDA is used.

**Pull request closed without merging**
